# https://github.com/marketplace/actions/secret-scan

# https://github.com/trufflesecurity/trufflehog

on: push
name: Find Secrets
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master